# Generated by Django 5.1.1 on 2026-06-21 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_bill_ipd_opd_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='', max_length=1),
        ),
        migrations.AddField(
            model_name='bill',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='bill',
            name='discount_note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='servicerate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
