# Generated by Django 5.1.1 on 2026-06-22 06:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_bill_age_pulse_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientBasicProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=200)),
                ('address', models.TextField(blank=True)),
                ('mobile_no', models.CharField(blank=True, max_length=15)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='', max_length=1)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('pulse_rate', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('has_diabetes', models.BooleanField(default=False)),
                ('has_high_bp', models.BooleanField(default=False)),
                ('has_heart_disease', models.BooleanField(default=False)),
                ('has_asthma', models.BooleanField(default=False)),
                ('has_recent_surgery', models.BooleanField(default=False)),
                ('is_pregnant', models.BooleanField(default=False)),
                ('has_thyroid', models.BooleanField(default=False)),
                ('has_kidney_disease', models.BooleanField(default=False)),
                ('condition_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue_number', models.PositiveIntegerField(help_text='Sequential number within the day')),
                ('status', models.CharField(choices=[('WAITING', 'Waiting'), ('WITH_DOCTOR', 'With Doctor'), ('DONE', 'Done')], default='WAITING', max_length=20)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_entries', to='billing.patientbasicprofile')),
            ],
            options={
                'ordering': ['date', 'queue_number'],
                'unique_together': {('date', 'queue_number')},
            },
        ),
    ]
