# Generated by Django 5.1.1 on 2026-06-22 08:33

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_patientbasicprofile_queue'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='reception_amount_collected',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='queue',
            name='reception_bill_type',
            field=models.CharField(blank=True, choices=[('OPD', 'OPD'), ('IPD', 'IPD')], default='OPD', max_length=3),
        ),
        migrations.AddField(
            model_name='queue',
            name='reception_line_items',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='queue',
            name='reception_paid_via',
            field=models.CharField(blank=True, choices=[('CASH', 'Cash'), ('UPI', 'UPI'), ('ONLINE', 'Online')], default='CASH', max_length=10),
        ),
    ]
