# Generated by Django 5.1.1 on 2026-06-22 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_queue_reception_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='advance_paid_via',
            field=models.CharField(blank=True, choices=[('CASH', 'Cash'), ('UPI', 'UPI'), ('ONLINE', 'Online')], default='CASH', max_length=10),
        ),
    ]
