# Generated by Django 5.1.1 on 2026-06-22 10:30

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0013_bill_advance_paid_via'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='partial_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='bill',
            name='partial_amount_via',
            field=models.CharField(blank=True, choices=[('CASH', 'Cash'), ('UPI', 'UPI'), ('ONLINE', 'Online')], default='CASH', max_length=10),
        ),
        migrations.AddField(
            model_name='metrics',
            name='total_partial_bills',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='metrics',
            name='total_partial_collected',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='bill',
            name='payment_status',
            field=models.CharField(choices=[('UNPAID', 'Unpaid'), ('PARTIAL', 'Partially Paid'), ('PAID', 'Paid')], default='UNPAID', max_length=10),
        ),
    ]
