# Generated by Django 5.1.1 on 2026-06-22 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0014_bill_partial_payment_metrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='callout',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
