# Generated by Django 5.1.1 on 2026-06-22 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0015_bill_callout'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartialCollectRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collect_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('collect_label', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partial_collect_requests', to='billing.bill')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
