# Generated by Django 5.1.1 on 2026-06-22 17:21

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0016_partial_collect_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='partially_collected',
            field=models.JSONField(default=list, help_text='Audit list of partial payments collected via reception.'),
        ),
        migrations.AddField(
            model_name='bill',
            name='total_partially_collected',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
