# Generated by Django 5.1.1 on 2026-06-22 18:31

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0017_bill_partially_collected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metrics',
            name='total_partial_collected',
        ),
        migrations.AddField(
            model_name='metrics',
            name='total_unsettled',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sum of net_bill across all PARTIAL bills (money still owed).', max_digits=14),
        ),
    ]
