# Generated by Django 5.1.1 on 2026-06-23 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0018_metrics_unsettled'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('role', models.CharField(choices=[('doctor', 'Doctor'), ('reception', 'Reception')], default='reception', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['username'],
            },
        ),
    ]
