# Generated by Django 5.1.1 on 2026-06-24 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0019_user'),
        ('billing', '0019_user_plain_password'),
    ]

    operations = [
    ]
