# Generated by Django 5.1.1

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0019_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='patient',
            field=models.ForeignKey(
                blank=True,
                help_text='Link to patient profile (source of truth for patient data)',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='bills',
                to='billing.patientbasicprofile'
            ),
        ),
    ]
