# Generated by Django 5.1.1
# Data migration to populate Bill.patient foreign key from existing bill data

from django.db import migrations


def populate_bill_patient_fk(apps, schema_editor):
    """
    For each Bill without a patient FK:
    1. Try to find existing PatientBasicProfile by (patient_name, mobile_no)
    2. If found: Link bill to existing profile
    3. If not found: Create new PatientBasicProfile from bill data
    4. Set Bill.patient to the profile
    """
    Bill = apps.get_model('billing', 'Bill')
    PatientBasicProfile = apps.get_model('billing', 'PatientBasicProfile')
    
    bills_processed = 0
    profiles_created = 0
    profiles_reused = 0
    
    for bill in Bill.objects.filter(patient__isnull=True).select_related():
        # Try to find existing profile by name + mobile (best match)
        profile = None
        
        if bill.mobile_no:
            # First try: exact match on name and mobile
            profile = PatientBasicProfile.objects.filter(
                patient_name__iexact=bill.patient_name,
                mobile_no=bill.mobile_no
            ).first()
        
        if not profile and bill.patient_name:
            # Second try: just name (in case mobile changed)
            # Take the most recent one
            profile = PatientBasicProfile.objects.filter(
                patient_name__iexact=bill.patient_name
            ).order_by('-created_at').first()
        
        if profile:
            # Found existing profile - reuse it
            profiles_reused += 1
        else:
            # No matching profile found - create new one from bill data
            profile = PatientBasicProfile.objects.create(
                patient_name=bill.patient_name or "Unknown Patient",
                address=bill.address or "",
                mobile_no=bill.mobile_no or "",
                gender=bill.gender or "",
                age=bill.age,
                weight=bill.weight,
                height=bill.height,
                pulse_rate=bill.pulse_rate,
            )
            profiles_created += 1
        
        # Link bill to profile
        bill.patient = profile
        bill.save(update_fields=['patient'])
        bills_processed += 1
    
    print(f"\n✅ Bill-Patient FK Migration Complete:")
    print(f"   - Bills processed: {bills_processed}")
    print(f"   - Existing profiles reused: {profiles_reused}")
    print(f"   - New profiles created: {profiles_created}")


def reverse_populate(apps, schema_editor):
    """
    Reverse migration: Remove patient FK from all bills.
    Data is preserved in the old fields, so this is safe.
    """
    Bill = apps.get_model('billing', 'Bill')
    Bill.objects.all().update(patient=None)
    print("\n↩️  Reversed: Cleared all Bill.patient foreign keys")


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0021_bill_patient_fk'),
    ]

    operations = [
        migrations.RunPython(populate_bill_patient_fk, reverse_populate),
    ]
