# Generated by Django 5.1.1
# IMPORTANT: Only run this after confirming all bills have patient FK populated!

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    """
    Makes Bill.patient foreign key required (removes null=True).
    
    WARNING: Only run this migration after:
    1. Running 0022_populate_bill_patient.py
    2. Verifying all bills have patient != None
    3. Testing that bill creation properly creates/links patient profiles
    
    To verify before running:
    >>> from billing.models import Bill
    >>> Bill.objects.filter(patient__isnull=True).count()
    >>> # Should return 0
    """

    dependencies = [
        ('billing', '0022_populate_bill_patient'),
    ]

    operations = [
        # First, ensure no NULL values exist (safety check)
        migrations.RunSQL(
            sql="""
                UPDATE billing_bill
                SET patient_id = (
                    SELECT id FROM billing_patientbasicprofile
                    WHERE patient_name = billing_bill.patient_name
                    LIMIT 1
                )
                WHERE patient_id IS NULL;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        
        # Now make the field required
        migrations.AlterField(
            model_name='bill',
            name='patient',
            field=models.ForeignKey(
                help_text='Link to patient profile (source of truth for patient data)',
                on_delete=django.db.models.deletion.PROTECT,
                related_name='bills',
                to='billing.patientbasicprofile'
            ),
        ),
    ]
