# Generated by Django 5.1.1 on 2026-06-25 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0023_bill_patient_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='address',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='age',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='height',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='mobile_no',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='patient_name',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='pulse_rate',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='weight',
        ),
        migrations.AlterField(
            model_name='bill',
            name='patient',
            field=models.ForeignKey(help_text='Patient profile (source of truth for patient demographics)', on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='billing.patientbasicprofile'),
        ),
    ]
